(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,615,461]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Растровоеизображение1 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tx2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AECDQIgIgDIgHgFQgCgDgCgFIgCgJIgBgcIgPAAIAAA1IgRAAIAAh7IARAAIAAA1IAPAAIABgcIACgJIAEgIIAHgFIAIgEIAJAAIAIAAIAJAEIAHAFIAEAIIADAJIAABJQAAAEgDAEIgEAIIgHAFQgEADgFABIgIABgAEEBlQgDACgBACIgCAHIgBAHIAAA4IABAHIACAGQACADACABQAEACADAAIAGgCQADgBACgDIACgGIABgHIAAg4IgBgHIgCgHQgCgCgDgCIgGgBQgDgBgEACgAmIDQIgMgDIgJgGQgEgDgDgGIgGgKQgBgFAAgHQAAgFACgJIAIgOIAJgLIAMgKIgLgJQgEgDgFgIQgDgGgDgHQgCgGAAgHQAAgGACgFIAEgKIAHgIQADgEAFgCIALgDIAKgCIALACIAKADQAFACAEAEIAHAIIADAKIACALQAAAHgCAGQgCAHgEAGQgEAHgEAEIgMAJIANAKIAJALQAEAFADAJQADAIAAAGQAAAIgCAEQgCAGgDAEQgDAGgFADQgEAEgGACIgKADIgKABgAmHCJIgIAIQgEAEgDAHQgDAGABAGQAAAGABAFQAEAFADACIAJAFIAKACQAFAAAFgCIAJgFQAEgDACgEQACgFAAgGQAAgGgCgGIgHgLIgIgIIgKgIIgKAIgAmGAzQgFACgDADIgFAHIgCAKQAAAFADAFIAFAKQADAEAFAEIAIAIIAJgIIAHgIIAGgKQACgFAAgFIgCgKQgCgFgDgCQgDgDgEgCQgFgBgFgBIgJACgAGJDPIAAg2IgzAAIAAA2IgSAAIAAh6IASAAIAAAzIAzAAIAAgzIASAAIAAB6gACfDPIADhkIgwBkIgXAAIAAh6IATAAIgDBkIAxhkIAWAAIAAB6gAg0DPIAAiYIghAZIgKgLIArgiIATAAIAACsgAnhDPIAAiYIgiAZIgKgLIAsgiIASAAIAACsgAH7DPIAAgvIgWAAIgfAvIgUAAIAfgwQgHgBgEgDIgKgJQgEgFgCgFQgBgHAAgHIABgKIADgKQACgEAEgEIAIgFQAFgCAFgBIAKgCIAzAAIAAB7gAHSBnQgEACgCAEIgEAHIgBAHIABAJQABAEADADQADADADACIAJABIAhAAIAAgrIghAAgAjPDPIAAgNIACgMIADgNIAFgMIAGgLIAJgJIAJgIIALgIIAKgIQAGgFACgEQAEgFACgGQABgGAAgGIgBgMIgFgKQgDgDgGgDQgEgDgHAAQgGAAgFACQgEABgEAEQgDADgBAGIgCAKIAAABIgTAAIAAgCIABgLIAFgLQACgFAFgEQADgEAGgDIALgEIALgBIANABQAHACAEADQAFACAFAGQAFAGACAEQADAGAAAFIABANQAAAHgBAGQgCAGgDAGQgCAFgGAHIgJAKQgDACgJAGIgKAJQgFAEgEAGQgFAFgDAFIgEANIgDANIBEAAIAAARgAlACIIAAgRIBlAAIAAARgAGighQgFgBgFgCQgGgDgEgEQgEgFgCgEIgFgLQgBgFAAgHIASAAIADAKQAAAFAFAEQAEAEAEACIALABIAJgBQAEgCAEgDIAFgHIADgJIABgJIAAgSIgBgJIgDgJIgFgHIgIgGIgIgCIgJABQgEABgEAEQgCABgDAFIgDAIIgSAAIAAheIBRAAIAAAQIg/AAIAAAxQAFgEAHAAIAMgBQAHAAAHACQAGABAGAEQAEAEAFAGQAEAGACAHQADAGAAAHIABAOIgBANIgDAOQgDAHgEAFQgEAGgFAEQgFAEgHACIgOABgADBghIgNgFQgFgDgEgEQgEgFgDgGQgDgHgBgGIgBgMIAAhOIABgNIAEgMQADgGAEgFQAFgFAEgDQAGgDAHAAIALgCQAHAAAGACIAMADQAGAEAEAEQADAEADAHQADAHABAFIAAANIAABPIAAAMQgBAFgDAHIgGALQgGAGgEACQgGADgGABIgNABIgLgBgACyhZIAAAQIACAHIAFAIIAFAGIAHACQACABAFAAIAJgBIAHgCIAFgGIAFgIIABgHIABg7gADEi/QgEABgEADIgFAFIgEAHIgCAIIgBA7IABAAIA2grIAAgQIgCgIIgEgHIgFgFQgFgDgDgBIgIgBgAkFghQgGgBgEgCQgFgDgFgEQgDgDgEgGIgDgLQgCgGAAgGIAAgCIASAAIAAABIACALQABAFAEAEQAEAEAEACIAMABQAEABAHgDQAFgCAEgFQAEgEAAgGQACgFAAgGIAAghIgpAAIAAgRIApAAIAAgfIgCgNQgBgFgDgFQgEgEgGgCQgFgDgGAAIgLABQgEADgFADQgCAEgDAFQgCAFAAAGIAAABIgRAAIAAgBIABgMIAEgKQACgFAFgFQAGgFADgCIALgDIAMgBIAMABQAJACADACQAEADAFAFQAGAFABAFQADAHABAEIABANIAABRIgBAMQgBAFgDAHQgBAEgGAGQgEAFgFADQgGADgGABQgGACgFAAgAESghIABgaIAEgMIAMgXIAIgKIAKgIIAUgQQAGgEACgFQAEgEABgHQACgGAAgGIgCgLQgBgGgDgFQgDgEgGgCQgGgDgFAAQgFABgFACQgFAAgEAFQgDADgCAFIgCALIAAABIgSAAIAAgCIABgMIAEgKQADgFAEgEQAFgFAEgCIALgDIAMgBIAMABIAMADQAEADAFAFQAEAFADAFIAEAMIABANQAAAGgBAHIgGANQgCAEgFAHIgKAJIgVASIgJAJIgHALIgGANIgCANIBEAAIAAARgAAwghIABgaQAAgHADgFIALgXIAJgKIAJgIIAVgQQAHgFACgEQADgFABgGIACgMIgCgLQgBgGgDgFQgCgDgHgDQgGgDgFAAQgEABgHACQgEAAgEAFQgDAEgCAEIgBALIAAABIgTAAIAAgCIACgMIADgKQADgFAFgEQADgEAGgDIAKgDIANgBIAMABQAHABAEACQAFADAEAFQAGAGABAEQADAIABAEIABANQAAAGgCAHQgBAGgDAHIgIALIgJAJIgVASIgKAJIgHALIgGANIgCANIBEAAIAAARgAiPghIAAgUIgDAAIgLgBQgGgCgEgEQgEgCgEgGIgFgKIgCgLIAAg9IACgLIAFgKQAEgGAEgCQAFgEAFgCQAGgBAFAAIADAAIAAgTIASAAIAAATIADAAIALABQAHACADAEQAFADADAFIAFAKIADALIAAA9QgBAIgCADQgBAFgEAFQgEAGgEACQgDAEgHACIgLABIgDAAIAAAUgAiZiqIgFAEIgEAHIgCAGIgBAHIAAA0IABAHIACAIIAEAFIAFAFQAEABADAAIAEAAIAAhnIgEAAQgDAAgEABgAh9hFIADAAQADAAADgBIAGgFIADgFIAEgHIABgIIAAg0IgBgHIgHgNQgCgDgEgBQgDgCgDAAIgDAAgAlOghIACiPIgXBaIgQAAIgXhaIACCPIgSAAIAAisIAWAAIAZBbIAYhbIAWAAIAACsgAnGghIAAicIgzAAIAACcIgSAAIAAisIBXAAIAACsgAhChpIAAgRIBlAAIAAARg");
	this.shape.setTransform(52.55,20.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx2, new cjs.Rectangle(0,0,105.1,41.8), null);


(lib.tx12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsIHEIAArEIBSAAIAABCIAJAAQAOgqApgWQAngWA8AAQBfAAAzAzQAyAyAABeIAACHQAABdgyAyQgzAzhfAAQg8AAgngVQgpgWgOgqIgJAAIAGBVIAADMgAqOiiQgiAhAAA/IAABoQAABAAiAhQAjAhBBAAQBAAAAighQAigiAAg/IAAhoQAAhAghggQgigihBAAQhCAAgiAigA1PHEIAArEIBSAAIAABCIAJAAQAOgqApgWQAmgWA8AAQBfAAAzAzQAyAyAABeIAACHQAABdgyAyQgzAzhfAAQg8AAgmgVQgpgWgOgqIgJAAIAFBVIAADMgAzViiQgjAhAAA/IAABoQAAA/AjAiQAiAhBCAAQBAAAAighQAigiAAg/IAAhoQAAg/gighQghgihBAAQhCAAgiAigAPnDSQgxgoAAhKQAAhMAygoQAygqBaAAICqAAIAAgcQAAg3gegZQgggahDAAQhDAAggAaQghAZAAA3IhUAAIAAgKQAAhRA7gvQA7gwBjAAQBlAAA6AwQA5AvAABRIAAFIIhSAAIAAhBIgIAAQgOAiggAVQguAehOAAQhbAAgwgmgAQTBcQAAApAdASQAcATA+gBQBQAAAjgfQAiggAAhJIAAgUIilAAQhnAAAABPgAG1DBQg+g3AAhjIAAkPQAAhrA3g4QA4g3BrAAIDgAAIAABZIjsAAQg8AAgfAhQgeAhAAA/IAAA3IAIAAQAUgmArgUQArgVA8AAQBjAAA1A2QA2A3AABkIAABWQAABig+A4Qg+A3hsAAQhuAAg9g3gAH0iPQgkAiAABHIAABEQAACLCSAAQCOAAAAiLIAAhDQAAiMiQAAQhJAAgjAigAigDSQgxgoAAhKQAAhMAygoQAygqBbAAICoAAIAAgcQAAg3gegZQgfgahEAAQhCAAggAaQggAZAAA3IhVAAIAAgKQAAhRA7gwQA6gvBkAAQBkAAA6AwQA6AvAABRIAAFIIhTAAIAAhBIgIAAQgOAiggAVQgtAehOAAQhaAAgxgmgAh0BcQAAApAdASQAdATA8gBQBRAAAigfQAiggAAhJIAAgUIikAAQhnAAAABPgA9wC/Qg9g5AAhkIgBAAIAAhgQAAhkA/g5QA/g5BqAAQBrAAA+A2QA9A2ADBhIAABLIl5AAIAAAUQAACQCRAAQCCAAANhzIBYAAQgGBdg6AzQg8AzhrAAQhtAAg+g5gA41hHQgJh9iHAAQiHAAgJB9IEgAAIAAAAgEAi6ADkIAAmVIjMAAIAAhPIHwAAIAABPIjMAAIAAGVgAdJDkIAAkMIAFhTIgJAAIjtFfIhaAAIAAnlIBYAAIAAEaQAAAUgBAKIgEA1IAKAAID4ltIBNAAIAAHlgEgkRADkIAAmVIjMAAIAAhPIHwAAIAABPIjNAAIAAGVgAa/ksQhKAAgogkQgpgkAAhBIAAgOIBUAAIAAASQAAA/BHAAIArAAQA+AAAAg/IAAgSIBUAAIAAAOQAABBgnAkQgmAkhFAAg");
	this.shape.setTransform(252.625,45.225);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx12, new cjs.Rectangle(0,0,505.3,90.5), null);


(lib.tx11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaCQIAAkZIAeAAIAAAkQACgIAGgJQAGgIAGgFQAKgGAGgBQAIgDAKAAQALAAAHADQAIACAJAGQAIAGAFAIIAIASQACAGABAMIAABUQgBAMgCAGIgIASQgGAIgHAFQgKAIgHABQgIACgKAAQgJAAgJgCQgIgDgIgFQgHgFgFgIQgEgGgEgKIAAB3gABVhuQgHABgFAEIgIAIIgGAMQgDAIAAAEIAABIIADALQADAIADADQACAFAGAEQAGAFAGABIANABIANgBQAIgDADgDIAJgJQAFgFABgGQACgHAAgEIAAhIIgCgMQgBgFgFgHIgJgIQgEgEgHgBIgNgBgArhCQIAAkZIAdAAIAAAkQADgIAGgJQAEgGAIgHQAJgGAHgBQAIgDAKAAQALAAAHADQAIACAJAGQAIAGAEAIIAJASQADAJAAAJIAABUQAAAIgDAKIgJASQgGAIgGAFQgKAIgHABQgJACgJAAQgKAAgIgCQgJgDgHgFQgIgFgEgIIgJgQIAAB3gAqmhuIgLAFIgJAIIgFAMQgDAIAAAEIAABIIADALQACAIADADQADAFAGAEQAFAFAGABIANABIANgBQAIgDAEgDIAJgJQAEgFABgGQADgHAAgEIAAhIIgDgMQgBgFgEgHIgJgIQgFgEgHgBIgNgBgAEKA9QgIgCgLgFQgJgFgGgIQgIgHgEgKQgEgJgCgLQgBgFAAgOIABhDQACgKAEgJQADgJAJgJQAGgHAJgFQALgGAIgCQAMgCAJAAQAKAAALACQAJACAKAGQAJAFAGAHQAHAIAFAKQAEAJACAKIABAVIgBBBQgCALgEAJQgFAMgHAFQgGAIgJAFQgKAFgJACIgVACgAEShvQgIACgEACQgFAEgEAFIgHAMQgDAIAAAFIAABIQAAAFADAGIAHALQACAGAHADIAMAGIANABIANgBQAHgCAFgEQAFgDAEgGIAHgLIADgLIAAhIIgDgNIgHgMQgEgFgFgEIgMgEQgEgCgJAAgAt/A8QgLgDgJgIQgKgKgDgKQgEgMAAgMQAAgKADgIQACgKAGgIQAGgGAJgHIARgIIASgEIA1gBIAAgTQAAgKgCgGQgCgHgHgGQgFgFgJgDQgLgDgFAAIgPACQgHABgGAEQgHADgDAHQgEAHAAAHIAAABIgeAAIAAgCQAAgJADgIQABgHAGgIQAIgKAEgDIAPgHQAKgDAHAAIARgCIATACQAIAAAJAEQAKAFAFAGQAIAGAEAIQAEAGADALQACAKAAAIIAACHIgfAAIAAghQgBAFgHALQgKAKgDACQgIAFgIACQgEADgLAAQgNAAgLgDgAtegbIgLACIgLADQgFACgFAFQgFAHgBACQgCAGAAAFQAAAIAEAGQAEAIAFAEQAGAFAIABIAQAAQAJAAAJgDQAIgDAGgGQAGgIACgIQADgHAAgJIAAgVIgiAAIgMABgAHKA9QgKgBgKgGQgJgFgGgIQgFgFgHgMQgEgJgCgLIAAhWQACgKAEgJQAEgKAIgIQAGgHAJgFQAKgGAKgCQAKgCAKAAQAKAAALACQAKACAJAGQAJAFAGAHQAIAKAEAIQAEAJACAKIABAVIAAAkIh2AAIABAXIADALQACAGAEAGQAEAFAGAEIAMAFQAEABAJAAIAPgBQAFgBAJgEQAGgDAEgIQAEgGAAgIIAeAAQAAAKgCAHQgDAIgGAIIgMAMIgPAIQgJADgIABgAHRhwIgNAFIgJAJIgGALIgEANIAAAWIBZAAIAAgWIgEgNIgGgLQgDgFgHgEIgLgFQgFgCgIAAgANNA9IAAirIg6AAIAAgbICSAAIAAAbIg6AAIAACrgAKPgZIgVAAIAABVIgdAAIAAjFIAdAAIAABVIAVAAIA2hVIAiAAIhABjIBABiIgiAAIAAABgAg1A9IAAirIhSAAIAACrIgdAAIAAjGICNAAIAADGgAnqA9IAAirIg7AAIAAgbICTAAIAAAbIg6AAIAACrgAlkgZIAAgbICOAAIAAAbg");
	this.shape.setTransform(93.275,14.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx11, new cjs.Rectangle(0,0,186.6,28.8), null);


(lib.shad1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["rgba(0,0,0,0.749)","rgba(0,0,0,0)"],[0,1],0,0,0,0,0,185).s().p("ArQaoQlLiMkAkAQkBkAiMlMQiRlWAAl6QAAl3CRlYQCMlMEBkAQEAkAFLiNQFZiRF3AAQF4AAFYCRQFMCNEAEAQEAEACNFMQCRFYAAF3QAAF6iRFWQiNFMkAEAQkAEAlMCMQlXCSl5AAQl3AAlZiSg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shad1, new cjs.Rectangle(-185,-185,370,370), null);


(lib.s3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANoCKIAAkPIAdAAIAAAkQADgIAEgIQAGgIAHgFQAIgFAGgCQAKgCAIAAQAKAAAIACQAJACAIAGQAHAGAEAIQAEAEAEANIAFARIAABPIgFASIgIARQgGAKgFADQgLAHgGACQgLADgHAAQgIAAgKgDQgIgCgGgFQgGgFgHgIQgFgHgCgJIAABzgAOihsQgFAAgHAEQgFADgEAHQgDAEgCAGIgDANIAABFIADALIAFALIAJAJQAGAFAGABIANABIALgBQAEgBAIgFQAGgEACgFQADgEACgHIADgLIACgNIAAgsIgCgMIgDgNIgFgKIgIgKQgEgDgIgBIgLgCgAMnB0IAAg6IhmAAIAAA6IgdAAIAAhUIALAAQAHgQACgGIAFgYQACgKAAgNIABhgIByAAIAAClIARAAIAABUgALagmQAAANgCALIgEAXQgEAOgDAJIBKAAIAAiMIg8AAgAiVB0IAAg6IhmAAIAAA6IgcAAIAAhUIAKAAQAHgLACgLIAGgYQABgKAAgNIABhgIBzAAIAAClIARAAIAABUgAjhgmQAAANgCALIgFAXQgCANgFAKIBLAAIAAiMIg9AAgARCA7QgJgCgLgKQgIgHgDgMQgEgLAAgLQAAgJACgHQACgKAGgHQAIgKAGgDQAKgFAHgDIASgDIA1gCIAAgSQgBgJgCgHQgCgGgHgGQgFgEgJgEQgIgCgIAAIgNABQgGABgIAEQgFAEgFAHQgDAGAAAHIAAAAIgcAAIAAgBQAAgJACgHQACgJAGgGQADgFAJgHQAFgEAJgEIARgEIAQgBIASABQAIAAAIAFQALAEAFAGQAGAFAFAJQAEAGACALQACAIAAAJIAACDIgcAAIAAggIgJAPQgEAFgIAHQgHAEgJADIgRABQgHAAgQgDgARigbIgMACIgKADIgKAGQgDAEgCAGQgDAFAAAEQAAAIAEAHQACAGAHAEQAJAGAEABIAQABQAJAAAIgDQAKgEAEgGQAEgEAFgKQACgIAAgHIAAgVIgiAAIgKAAgAInA7QgLgBgIgGQgKgGgEgGQgHgGgFgLQgEgKgBgJIAAhUQABgKAEgIQAEgLAIgGQAJgKAFgDQAJgFAKgCQAKgCAKAAQAKAAAKACQAJACAJAFQAKAGAFAHQAHAGAEALQAFAKAAAIIACA4IhzAAIABAVIACALQADAHAFAEQADAGAFADIALAFIANACIAPgCIANgFQAIgFADgFQAEgHAAgIIAdAAQgBAKgDAHQgDAKgEAFQgEAGgIAGIgPAIQgIADgIABQgIADgJAAQgKAAgKgDgAIuhsQgFABgGAEQgEACgFAHQgFAEgCAGQgDAJAAAEIAAAVIBVAAIAAgVIgDgNQgCgFgEgFIgKgJQgHgEgEgBIgMgBgAu7A9QgMgCgGgCQgGgBgJgFQgHgEgFgHQgGgGgDgHQgDgIAAgJIAAgCIAdAAIAAABQAAAGACAEIAGAHIAIAEIAKAEIATACIAPgBQAGgBAJgGQAHgEADgGQAEgHABgJIgCgIQgDgIgDgCIgIgGIgKgDIgKgCIgggBIAAgaIAfgBIAJgCIAIgDIAHgGIAFgHIABgJQAAgHgDgHQgDgFgGgFIgNgFIgNgBIgOABQgHACgFADQgGADgDAGQgFAFABAGIAAABIgeAAIAAgCQAAgJAEgHQACgGAGgHQAGgIAFgDIAPgGIAPgEIAgAAIAQAEIAPAHIALALQAGAGABAKQADAKAAAFIgCAOQAAAFgFAGQgFAHgEACQgEADgIAEQAGABAIAGIAKAKQAGAFACAHQACAJAAAGQAAAKgCAIQgCAJgGAHQgGAHgGAEQgFADgLAFQgEABgOADQgIAEgLAAgAE+A7IAAjAIAcAAIAABQIBQAAIAAhQIAdAAIAAC/IgdAAIAAhVIhQAAIAABWgAAYiFIBHAAIAPAAIAPADQAJAFAFADQAFAEAFAHQAEAHACAIQACAGABAJQAAAHgCAFQgBAHgEAEQgDAFgGAFIgKAHQAIACAGAEIAMAKQADAEAEAJQACAIAAAGQAAAJgCAIQgCAHgGAJQgGAHgHAEQgKAGgFACQgGACgLABIhYABgAA0AgIA2gBIAJgCIAJgDIAIgGQAFgDAAgFIACgKIgCgIQgBgGgEgEIgIgGIgJgDIgJgCIg2AAgAA1g1IArAAIAMgBIAMgGQADgBAEgIQADgGAAgFQAAgIgDgEQgCgFgFgFIgMgEIgMgCIgrAAgAlYA6IAAhKIgiAAIgyBKIgiAAIAyhKQgLgCgIgFQgLgGgDgHQgHgJgCgJQgCgLAAgKIABgQQABgHAEgIQAEgGAGgGIANgJIAPgFIAQgBIBQAAIAAC/gAmYhpQgHACgEAGQgGAGgBAEIgBANIABANQACAHAFAEQADAEAIADQAFACAHAAIAzAAIAAhCIgzAAQgHAAgFACgAqQAgIALgCQAEgBADgGIAFgIIAEgUIABiCICBAAIAADAIgfAAIAAilIhFAAIgDB3IgEAPQgFAMgCACQgEAGgHAFQgLAFgEABIgRABgAssA6IAAi/ICBAAIAAAZIhkAAIAACmgAyqiFIBXAAIAPADQAIAEAFAEQAGAFAEAGQAEAHADAIQACAHAAAIIgCAMQAAAHgEAEQgDAGgGAEIgKAHIAOAGIALAKQAEAEACAJQACAIAAAGQAAAJgCAIQgBAHgGAJQgFAHgIAEIgPAIQgGACgLABIhYABgAyNAgIA1gBIAKgCIAJgDIAIgGQADgEABgEIACgKIgCgIQgBgFgDgFIgIgGIgJgDIgKgCIgLAAIgqAAgAyNg1IA4gBIALgGQAEgCAEgHQACgGAAgFQAAgIgCgEQgCgEgGgGIgLgEIgNgCIgrAAg");
	this.shape.setTransform(119.5,13.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s3, new cjs.Rectangle(0,0,239,27.6), null);


(lib.s1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AihCwIAAkPIAdAAIAAAkIAIgQQAHgJAFgDQAKgHAFgBQAJgCAJAAQAJAAAJACQAJAEAHAFQAGAEAGAJQAFAGADALQACAHACAKIAABQQgBAJgDAIIgIARIgMAOQgHAFgJADQgLADgHAAQgJAAgJgCQgIgCgHgFQgFgEgHgKQgFgGgDgKIAABzgAhnhFQgFAAgGAEQgGAEgDAFQgDADgCAJIgDALIAABFIADAMQABAFAEAFIAJAKQAFAEAGABQAEABAIAAIANgBQAFgBAHgEQAFgFADgFQADgDACgHIAEgMIAAhFIgEgLQgCgIgDgEIgIgJQgGgDgGgBIgNgCgAkjCwIAAhMIgFAAQgKAAgHgDQgJgCgIgGQgGgFgFgJQgEgDgEgOQgCgEgBgNIAAhQIADgRIAIgRQAHgJAEgEIARgJQALgCAGAAIAFAAIAAhNIAcAAIAABNIAEAAQALAAAHACQAJAEAHAFQAGAEAGAJQAFAGADALQACAEACANIAABQIgEARQgDALgFAGIgMAOQgHAFgJADQgLADgHAAIgEAAIAABMgAkHBMIAEAAQAFAAAHgCQADgCAGgFQADgCACgIIAEgLIACgXIAAg2IgCgLIgEgLIgFgKIgJgGQgHgDgFgBIgEAAgAkyhGQgEABgFAFQgDADgDAHIgFAWIAAA3IACAXIADALIAGAJIAJAIQAFABAGAAIAFAAIAAiUIgFAAQgGAAgFADgApKCcIAAg7IiCAAIAAjAIAdAAIAACnIBQAAIAAinIAcAAIAACnIARAAIAABUgAG7BiQgLgDgHgEQgKgGgFgHQgHgHgFgKQgFgKAAgJIgBgUIABg/QABgKAEgJQAGgLAGgGIAPgMQAIgGAKgCQAKgCAKAAQAKAAAKACQAIACAKAGQALAGAEAGQAHAIAFAJQAEAKABAJIACA/IgCAUQgBAKgEAJQgEAJgIAIQgJAJgGAEQgIAFgKACQgKACgKAAQgKAAgKgCgAHChEQgEAAgGAEQgGAEgEAEQgFAGgCAGIgCAMIAABEIACAMQACAFAFAGQADAFAHAEQAGAEAEABQAEABAJAAIANgBQAEgBAHgEQAEgDAEgGQAGgHABgEQADgIAAgEIAAhEIgDgMQgBgFgGgHQgEgFgEgDQgHgEgEAAIgNgBgABIBiQgKgCgIgFQgKgGgFgHQgIgIgEgJQgEgKgBgJIAAhTQABgKAEgJQAFgJAHgIQAJgIAGgEQAKgGAIgCIAUgCQALAAAJACQAKACAIAGQALAGAFAGQAGAGAFALQAFAKAAAJIABA/IgBAUQAAAKgFAJQgFAKgGAHIgQANQgGAEgMADQgJACgLAAQgKAAgKgCgABQhEQgFAAgGAEQgGADgDAFIgIAMIgCAMIAABEIACAMIAIALQADAGAGADQAGAEAFABQAEABAIAAIANgBQAEgBAHgEQAGgEADgFQAEgGADgFQACgIAAgEIAAhEIgCgMQgDgGgEgGQgDgEgGgEIgLgEIgNgBgAKxBhIADieIhNCeIgkAAIAAjAIAdAAIgECfIBOifIAjAAIAADAgADQhfIBXABIAPAEQAIADAGAEQAGAFAEAHQAEAGACAHQACAIAAAIIgBAMQgBAHgEAFQgCAEgGAEIgLAIQAIACAGAEQAHAEAEAFQAFAEADAKQABAHAAAIQAAAIgBAIQgCAJgHAHQgDAGgJAFIgQAIQgFACgMABIhYABgADtBIIA1gCIAKgCIAJgDQACgBAFgFQAFgEAAgEQACgFAAgFQAAgEgCgGQAAgEgFgEIgHgHIgJgDIgKgCIg1gBgADugOIAqAAIANgBQAFgBAGgEQAEgCAEgIQACgGAAgFQAAgHgCgFQgCgGgGgDIgLgFIgNgBIgqAAgAmmBhIAEieIhNCeIgkAAIAAjAIAdAAIgDCfIBMifIAjAAIAADAgAJyh/QgLgDgIgHQgJgIgDgJQgEgLAAgLIAaAAQAAAFACAHQABAGAGAEQADADAIADIALABIAMgBQAFgBAGgFQAEgEACgGQADgJAAgDIAaAAQAAAMgFAKQgEAJgIAIQgHAHgMADQgJADgNAAQgNAAgJgDg");
	this.shape.setTransform(71.7,17.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.s1, new cjs.Rectangle(0,0,143.4,35.3), null);


(lib.ligal = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAOA5IAAhkIgbAAIAABkIgPAAIAAhxIA5AAIAABxg");
	this.shape.setTransform(4.2,20.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AARA5IgFgaIgXAAIgFAaIgQAAIAYhxIARAAIAYBxgAgBgaIgHAqIARAAIgJgxIgBAHg");
	this.shape_1.setTransform(11.075,20.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIA6IgIgDIgHgFQgDgEgBgDIgDgIIAAhFIADgIQABgDADgDIAHgGIAIgCIAIgBIAIABIAIACIAGAGQAEADABADIACAIIABAJIAAAzIgBAJQgBAFgBADQgBADgEAEIgGAFIgIADIgIABgAgGgqQgEABgBADQgCACgBAEIgBAHIAAAzIABAHIADAGQABACAEACIAGABIAGgBQADgBACgDIADgGIABgHIAAgzIgBgHIgDgGQgCgDgDgBQgCgCgEAAQgEAAgCACg");
	this.shape_2.setTransform(17.95,20.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMATIgIgIIgIgIIAAgFIAIgHIAIgJIAKgVIAMAEIgKATQgGALgGAFQAGAGAGALIAKATIgMAEgAgRATIgHgIQgEgFgFgDIAAgFIAJgHIAHgJIALgVIAKAEIgIATQgHALgGAFQAGAGAHALIAIATIgKAEg");
	this.shape_3.setTransform(31.6,20.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbA5IAAhxIA3AAIAAANIgnAAIAABkg");
	this.shape_4.setTransform(38.75,20.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQABgFACgCIAGgFIAIgDIAIgCIAHAAIALAAIAAgHIgBgFIgDgFIgFgCIgFgBIgEAAIgFACIgDAEIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAHgBIAHABIAHACIAHAEIAFAGIADAHIAAA9IgPAAIAAgNIgEAGIgEAFIgHADIgGABIgJgCgAgDAGIgEABIgDACIgDAEIAAAEIABAFIADADQABABAAAAQABAAAAABQABAAABAAQAAAAABAAIAEABIAGgBIAFgDIADgGIABgGIAAgHIgLAAg");
	this.shape_5.setTransform(45.225,22.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGApIgHgBQgEgBgDgCQgDgBgDgEIgEgGIAAgHIAAgBIAPAAIAAABQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAIAEADIAFACIAKgBQACAAADgBIADgEIACgGIgBgDIgBgDIgDgDIgIgCIgMAAIAAgMIAJAAIAEgBIAEgBIAEgEIACgEIgCgFQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIgEgCIgFAAIgDAAIgFACIgEADIAAAEIAAABIgQAAIAAgCIABgGIADgGIAFgFQADgCAEgBQADgBADAAIAGgBIAHABIAHABIAGAEIAFAEQADADAAAEIABAHIAAAFIgDAFIgDADIgEADIAFACIAFAEIACAGIABAGIgBAHIgEAHIgFAFIgHADIgIACIgHABg");
	this.shape_6.setTransform(52.2,22.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAOApIAAhCIgbAAIAABCIgPAAIAAhRIA5AAIAABRg");
	this.shape_7.setTransform(59,22.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdA6IAAhyIAQAAIAAAPIACgGIAGgGQABgCAEgBIAGgBIAIABQAEACADACIAEAGIAEAHIABAHIAAAhIgBAHIgEAHIgEAGQgDADgEAAIgIACIgGgBIgFgEIgGgFIgCgGIAAAwgAgFgqIgGAFIgCAGIAAAHIAAAYIACAGIAGAFIAFABIAGgBIAGgFIACgGIAAgGIAAgZIgCgGIgGgFQgDgBgDAAQgCAAgDABg");
	this.shape_8.setTransform(65.9,23.675);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgHApIgIgDIgHgFIgFgHIgCgIIAAgjIACgIIAFgHIAHgFIAIgDIAHgBIAJABIAHADIAHAFIAFAHIACAIIAAAjIgCAIIgFAHIgHAFIgHADIgJABgAgGgaIgFAFIgCAGIgBAHIAAARIABAHIACAGIAFAFIAGABIAHgBQADgCACgDIADgGIAAgHIAAgYQgBgEgCgCQgCgDgDgCQgDgBgEAAg");
	this.shape_9.setTransform(72.675,22.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AARApIAChBIgNBBIgLAAIgOhBIACBBIgOAAIAAhRIAUAAIALA1IAMg1IAUAAIAABRg");
	this.shape_10.setTransform(79.55,22.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAOApIAAgjIgbAAIAAAjIgQAAIAAhRIAQAAIAAAhIAbAAIAAghIAQAAIAABRg");
	this.shape_11.setTransform(93.225,22.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHApIgIgDQgGgDgBgCIgFgHIgDgIIAAgjIADgIIAFgHQABgCAGgDIAIgDIAHgBIAIABIAIADQAFADABACIAGAHIACAIIAAAYIgsAAIAAAJIADAGIAFAFIAGABIAFgBQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQADgCAAgCQACgCgBgDIAQAAIgBAHQgBAEgCADIgFAFIgHADIgHACIgHABgAgGgaIgFAFQgBABgCAFIAAAHIAAACIAdAAIgBgJIgCgGIgGgFIgGgBg");
	this.shape_12.setTransform(100.1,22.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgHBKIAAggIgIgBIgHgEIgFgFIgDgHIgCgIIAAgIIAAgZIACgIIADgHIAFgFIAHgEIAIgBIAAggIAPAAIAAAgIAIABIAHAEIAFAFIADAHIACAIIAAAZIAAAIIgCAIIgDAHIgFAFIgHAEIgIABIAAAggAAHAeIABAAIAEgBIADgDIACgEIACgEIAAgEIAAgbIAAgEIgCgEIgCgEIgDgDIgEgBIgBAAgAgLgcIgDADIgCAEIgCAEIAAAEIAAAbIAAAEIACAEIACAEIADADIAEABIABAAIAAg7IgBAAg");
	this.shape_13.setTransform(106.925,22.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgHApIAAhCIgWAAIAAgPIA8AAIAAAPIgXAAIAABCg");
	this.shape_14.setTransform(113.75,22.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgdgoIAPAAIAAAeIAZABIAHACIAFAEIAEAFIADAGIAAAHIAAAHIgDAHIgEAFIgFAEIgHACIgoABgAgOAbIASAAIAFgBIADgDIACgDIABgFIgBgEIgCgFIgDgCIgFgBIgSAAg");
	this.shape_15.setTransform(120.675,22.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAkQADgLAFgIQAFgKAHgHQgHgGgFgKQgFgIgDgLIAKgEIAEALIAGAKIAIAJQAFAEAEADIAAAFQgFADgEAFIgIAIIgGAKIgEALgAghAkQAEgLAFgIQAGgKAHgHQgHgGgGgKQgFgIgEgLIAMgEIAEALIAGAKIAIAJIAHAHIAAAFIgHAIIgIAIIgGAKIgEALg");
	this.shape_16.setTransform(127.5,20.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AADBFIgJgLIgIgNQgEgJgBgGIgDgPIgBgPIABgOIADgPQABgGAEgJIAIgNIAJgLIAOgJIAHAMQgJAFgGAHQgGAJgDAHIgGATIgCASQABAKABAJIAGATQADAHAGAJQAGAHAJAFIgHAMIgOgJg");
	this.shape_17.setTransform(141.35,20.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAOA5IADhWIgdBWIgQAAIAAhxIAPAAIgCBWIAbhWIARAAIAABxg");
	this.shape_18.setTransform(148,20.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAOA5IAAg0IgbAAIAAA0IgPAAIAAhxIAPAAIAAAwIAbAAIAAgwIAPAAIAABxg");
	this.shape_19.setTransform(154.85,20.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAOA5IAAg0IgbAAIAAA0IgPAAIAAhxIAPAAIAAAwIAbAAIAAgwIAPAAIAABxg");
	this.shape_20.setTransform(161.7,20.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgHA5IgIgCIgGgFIgEgGIgDgHIgCgIIAQAAIABAGQABACADADIAEADIAFABIAFgBIAEgDIADgFIACgKIAAgKIgBgGIgBgFIgCgEIgFgCIgEgBIgFAAIgEACIgDADIgCAFIgPAAIAAhAIA2AAIAAAOIgnAAIAAAcIAHgCIAHAAIAJABQADABAFADQADACACAFIAFAHIABAJIABAJIgBAJIgBAJIgFAIIgGAHIgIADIgJACg");
	this.shape_21.setTransform(175.45,20.475);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgHA5IgIgCIgFgFIgGgGIgCgHIgBgIIAPAAIABAGQABACADADIAEADIAFABIAFgBIAEgDIADgFIADgKIAAgKIgCgGIgBgFIgDgEIgDgCIgGgBIgEAAIgEACIgDADIgCAFIgPAAIAAhAIA2AAIAAAOIgnAAIAAAcIAHgCIAGAAIAJABQAFABAEADQADACADAFIAEAHIABAJIABAJIgBAJIgBAJIgEAIIgHAHIgIADIgJACg");
	this.shape_22.setTransform(182.3,20.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgFIgFgHIgCgIIAAhFIACgIIAFgGIAHgGIAIgCIAHgBIAJABIAIACIAGAGQADADACADIACAIIAABFIgCAIQgCADgDAEIgGAFIgIADIgJABgAgOATIAAAHIABAHIACAGIAFAEIAGABIAHgBQADgCACgCIADgGIAAgkgAgGgqQgCABgDADIgCAGIgBAHIAAAeIAdgXIAAgOQgBgEgCgCQgCgDgDgBQgDgCgEAAQgCAAgEACg");
	this.shape_23.setTransform(189.075,20.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAGA5IAAgdIgjAAIAAgNIAihHIAPAAIgiBHIAUAAIAAgZIAPAAIAAAZIAJAAIAAANIgJAAIAAAdg");
	this.shape_24.setTransform(195.875,20.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgFIgFgHIgCgIIAAhFIACgIIAFgGIAHgGIAIgCIAHgBIAJABIAHACQAFADACADQADADACADIACAIIAABFIgCAIQgCADgDAEQgCACgFADIgHADIgJABgAgOATIAAAHIABAHIACAGIAFAEIAGABIAHgBQADgCACgCIADgGIAAgkgAgGgqQgCABgDADIgCAGIgBAHIAAAeIAdgXIAAgOQgBgEgCgCQgCgDgDgBQgDgCgEAAQgCAAgEACg");
	this.shape_25.setTransform(202.775,20.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAIABAHQABAEACACIAGADIAFAAIAHgBIAFgDIADgHIABgHIgBgGQAAgCgCgDQAAgDgDgCIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIAAAGIAAABIgQAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABQAFAAACACQADACADADQADACACAEQABACABAGIABAIIgBAIIgDAHQgBADgDADIgHAFIAIAEIAFAHIAEAIIABAIIgBAJQgBAEgCAEQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_26.setTransform(209.675,20.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgIA5IgIgEIgHgGIgEgIIgCgIIgBgJIABgOIAEgMIAYg1IAQAAIgXAyIAHgFIAIgCIAIACQAEACACACIAFAHIADAGIACARIgBAJIgCAIIgEAIIgHAGIgIAEIgJABgAgDAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAEIgCAEIAAAFIAAAIIABAFIACAEIADAFQACACACAAIAEABIAFgBIAEgCIADgFIACgEIABgFIAAgKIgBgGIgCgEIgDgEQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBgBIgFAAg");
	this.shape_27.setTransform(216.475,20.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABIAHACQADACADADQADACACAEIACAIIABAIIgBAIIgDAHQgBADgDADIgHAFIAHAEQAEAEACADIAEAIIABAIIgBAJQgBAEgCAEQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_28.setTransform(223.375,20.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFQACgCAAgCIABgGIgBgGIgDgFQgBgDgDgCQgCgBgEAAIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFIAGgFQAEgDADABIAHgBIAIABIAHACQADACADADQADACACAEIACAIIABAIIgBAIIgDAHIgEAGQgDAEgEABIAHAEQAEAEACADQADAEAAAEIACAIIgBAJQgBAEgCAEIgFAHIgHAFIgIADIgIABg");
	this.shape_29.setTransform(230.225,20.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgHA6IgIgDIgHgEIgFgHIgDgHIgBgIIAAgBIAQAAIAAAAQAAAEABADQABAEACACIAGADIAFAAIAHgBQADgBACgCIADgHIABgHIgBgGIgCgFIgDgFIgFgDIgFgBIgFgBIAAgNIAJgBIAEgDIADgFIACgEIAAgGIAAgGQgBgEgCgBQgBgDgDgCIgGgBIgFABIgEAEIgDAFIgBAGIAAABIgPAAIAAgBIABgIIACgIIAFgFQACgDAEgCQAEgDADABIAHgBIAIABIAHACIAGAFQADACACAEIACAIIABAIIgBAIIgDAHIgFAGQgCADgEACIAHAEQAEAEACADQADAEAAAEIACAIIgBAJIgDAIQgCAEgDADIgHAFIgIADIgIABg");
	this.shape_30.setTransform(237.075,20.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgXBCQAIgEAHgIQAHgIACgIQAEgKACgJQABgJAAgKIgBgSQgCgJgEgKQgCgIgHgIQgHgIgIgEIAIgMIAMAJQAGAGAEAFQAFAGADAHIAFAPIADAPIABAOIgBAPIgDAPIgFAPQgEAIgEAFQgEAFgGAGQgFAFgHAEg");
	this.shape_31.setTransform(243.675,20.825);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgIA5IgIgEIgHgGIgEgIIgCgIIgBgJIABgOIAEgMIAYg1IAQAAIgXAyIAHgFIAIgCIAIACQAEACACACIAFAHIADAGIACARIgBAJIgCAIIgEAIIgHAGIgIAEIgJABgAgDAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAEIgCAEIAAAFIAAAIIABAFIACAEIADAFQACACACAAIAEABIAFgBIAEgCIADgFIACgEIABgFIAAgKIgBgGIgCgEIgDgEQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBgBIgFAAg");
	this.shape_32.setTransform(276.475,15.075);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgEAgIAAgbIgcAAIAAgJIAcAAIAAgbIAJAAIAAAbIAcAAIAAAJIgcAAIAAAbg");
	this.shape_33.setTransform(285.1,16.125);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgdA5IAAhxIAcAAIAIABIAIADIAHAGIAFAHIADAJIAAARIgDAJIgFAGIgHAFIgIAEIgIAAIgMAAIAAAugAgNgBIAMAAIAFAAIAEgDIADgEIACgEIACgKIgCgJIgCgFIgDgDIgEgDIgFgBIgMAAg");
	this.shape_34.setTransform(4.15,3.35);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgIApIgIgDQgFgDgBgCIgFgHIgCgIIAAgjIACgIIAFgHQABgCAFgDIAIgDIAIgBIAIABIAIADQAFADACACIAEAHIADAIIABAYIguAAIABAJIADAGIAFAFIAGABIAFgBQADAAACgBIADgEQABgCABgDIAQAAIgCAHQgBAEgCADIgGAFIgFADIgIACIgHABgAgGgaIgFAFQgBABgBAFIgCAHIAAACIAeAAIAAgJQgBgEgDgCIgEgFQgDgBgEAAIgGABg");
	this.shape_35.setTransform(10.8,5.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAMApIgRgiIgHAAIAAAiIgRAAIAAhRIARAAIAAAjIAHAAIARgjIASAAIgYAoIAYApg");
	this.shape_36.setTransform(17.85,5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AASApIAAhCIgXAAIAAAZIgBARIgBAGIgFAKIgEAEIgFACIgFACIgGAAIAAgOIAEgBIADgCIACgDIABgEIABgJIAAgwIA2AAIAABRg");
	this.shape_37.setTransform(24.125,5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQAAgDAEgEQACgDADgCIAHgDIAJgCIAHAAIALAAIgBgMIgDgFIgFgCIgGgBIgDAAIgFACIgEAEIAAAFIAAAAIgQAAIAAgBIABgHQABgDACgDIAFgFIAHgEIAHgBIAFgBIAIABIAHACIAHAEIAEAGIADAHIABAHIAAA2IgPAAIAAgNQgBAEgCACIgGAFIgGADIgFABQgGAAgEgCgAgDAGIgEABIgEACIgBAEIgBAEIABAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgNIgLAAg");
	this.shape_38.setTransform(31.25,5.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AASApIAChBIgOBBIgLAAIgOhBIACBBIgOAAIAAhRIAUAAIALA1IALg1IAVAAIAABRg");
	this.shape_39.setTransform(38.125,5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgCgCgCgGQgCgEAAgFIABgIQABgFACgCQADgDAEgCIAHgDIAIgCIAGAAIAMAAIAAgHIgBgFIgDgFIgFgCIgGgBIgDAAIgFACIgDAEIgBAFIAAAAIgQAAIAAgBIABgHQAAgDADgDIAFgFIAHgEIAGgBIAGgBIAIABIAIACIAGAEIAEAGIADAHIABA9IgPAAIAAgNIgEAGIgEAFIgHADIgGABQgFAAgEgCgAgDAGIgEABIgDACIgDAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDIADgGIABgGIAAgHIgMAAg");
	this.shape_40.setTransform(44.9,5.025);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgFANQgCAAgDgDQgCgBgBgDIAAgGIAAgFQABgCACgDQADgCACgBIAFAAIAFAAQAEABABACQADADAAACIABAFIgBAGQgBADgCABQgBACgEABIgFABg");
	this.shape_41.setTransform(51.825,7.775);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgcA5IAAhxIAcAAIAHABIAJADIAGAGQADADACAEIACAJIAAARIgCAJIgFAGIgGAFIgJAEIgHAAIgNAAIAAAugAgNgBIANAAIADAAQADgBACgCQAAAAABgBQAAAAABgBQAAAAAAgBQABAAAAgBIACgEIABgFIAAgKIgBgEIgCgFQAAAAgBgBQAAAAAAgBQgBAAAAgBQgBAAAAAAQgCgCgDgBIgDgBIgNAAg");
	this.shape_42.setTransform(65.725,3.35);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgIApIgIgDIgGgFQgDgDgBgEQgCgCgBgGIgBgJIAAgRIABgJIADgIQABgEADgDIAGgFIAIgDIAIgBIAIABIAJADIAGAFQADADABAEIADAIIABAJIAAAPIgtAAIAAAJIADAGQACADADACIAGABIAFgBQADAAACgBIAEgEQABgCAAgDIAPAAIgBAHIgDAHIgFAFIgGADIgHACIgIABgAgGgaQgDACgCADIgDAGIAAAJIAeAAIAAgCIgBgHQgBgEgDgCQgBgDgDgCQgDgBgEAAQgCAAgEABg");
	this.shape_43.setTransform(72.35,5.025);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAMApIgSgiIgHAAIAAAiIgPAAIAAhRIAPAAIAAAjIAHAAIASgjIARAAIgXAoIAXApg");
	this.shape_44.setTransform(79.425,5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AARApIAAhCIgWAAIAAAfIgCARIgCAFIgDAFIgEAEIgFACIgGACIgFAAIAAgOIAEgBIADgCIACgDIACgIIAAgFIAAgDIAAgtIA2AAIAABRg");
	this.shape_45.setTransform(85.7,5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQABgFACgCIAGgFIAIgDIAIgCIAHAAIALAAIAAgHIgBgFIgDgFIgFgCIgFgBIgEAAIgFACIgDAEIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAHgBIAHABIAHACIAHAEIAFAGIADAHIAAA9IgPAAIAAgNIgEAGIgFAFIgGADIgGABIgJgCgAgDAGIgEABIgDACIgDAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgGIAAgHIgLAAg");
	this.shape_46.setTransform(92.825,5.025);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AARApIADhBIgPBBIgKAAIgOhBIADBBIgPAAIAAhRIAUAAIALA1IAMg1IAUAAIAABRg");
	this.shape_47.setTransform(99.75,5);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgHApIgIgDIgHgFIgFgHIgCgIIAAgjIACgIIAFgHIAHgFIAIgDIAHgBIAJABQAGABACACIAGAFQADADACAEIACAIIAAAjIgCAIQgCAEgDADIgGAFIgIADIgJABgAgGgaIgFAFIgCAGIgBAHIAAARIABAHIACAGIAFAFIAGABIAHgBQADgCACgDIADgGIAAgHIAAgYQgBgEgCgCQgCgDgDgCQgDgBgEAAg");
	this.shape_48.setTransform(106.575,5.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AATA1IAAgYIgkAAIAAAYIgQAAIAAgmIAEAAIAEgJIACgIIABgyIAxAAIAABDIAHAAIAAAmgAgIgCIgDAIQAAAFgDAEIAaAAIAAg0IgTAAg");
	this.shape_49.setTransform(113.45,6.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgPAoQgFgBgDgEQgDgCgCgGQgBgEAAgFIABgIQAAgDADgEQADgDADgCIAIgDIAHgCIAIAAIALAAIAAgHIgBgFIgDgFIgFgCIgGgBIgEAAIgEACQgBABAAAAQgBAAAAABQgBAAAAABQAAAAAAABIgCAFIAAAAIgPAAIAAgBIABgHIADgGIAFgFIAGgEIAHgBIAGgBIAIABIAHACIAHAEIAFAGIACAHIABAHIAAA2IgPAAIAAgNIgEAGIgFAFIgGADIgGABgAgHAHIgEACIgCAEIgBAEIACAFIADADIAFACIAEABIAGgBIAFgDQACgCABgEIABgGIAAgHIgLAAg");
	this.shape_50.setTransform(120.225,5.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgHApIAAhCIgWAAIAAgPIA7AAIAAAPIgWAAIAABCg");
	this.shape_51.setTransform(127.15,5);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgIApIgIgDIgGgFIgFgHIgCgIIAAgjIACgIIAFgHIAGgFIAIgDIAIgBIAIABIAIADQAFADACACIAEAHIADAIIAAAYIgtAAIABAJIADAGIAFAFIAGABIAFgBQADAAACgBIADgEIACgFIAPAAIgBAHQgBAEgCADIgGAFIgFADIgIACIgHABgAgGgaIgFAFQgBABgCAFIgBAHIAAACIAeAAIAAgJQgBgEgDgCIgEgFQgDgBgEAAIgGABg");
	this.shape_52.setTransform(134,5.025);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AASApIAAhCIgXAAIAAAZIgBARIgBAGIgFAKIgEAEIgFACIgFACIgGAAIAAgOIAEgBIADgCIACgDIABgEIABgJIAAgwIA2AAIAABRg");
	this.shape_53.setTransform(140.475,5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgdgoIAQAAIAAAeIAYABIAHACIAFAEIAFAFIACAGIAAAHIAAAHIgCAHIgFAFIgFAEIgHACIgoABgAgNAbIARAAIAFgBIADgDIACgDIABgFIgBgEIgCgFIgDgCIgFgBIgRAAg");
	this.shape_54.setTransform(147.725,5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgFApQgCgBgDgCIgDgFIAAgGIAAgFIADgFQADgDACAAIAFgBIAGABQACAAADADIACAFIABAFIgBAGIgCAFQgDACgCABIgGABgAgFgNIgFgDIgDgFIAAgFIAAgGIADgFIAFgDIAFgBIAGABIAFADIACAFIABAGIgBAFIgCAFIgFADIgGABg");
	this.shape_55.setTransform(154.525,5.025);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AhaBaQgQgQgJgSQgNgaAAgeQAAgeANgZQAJgTAQgQQAmglA0AAQA1AAAmAlQAlAmABA0QgBA1glAlQgmAmg1AAQg0AAgmgmgAhThTQgZAagHAgQgDANAAAMQAAANADAMQAHAiAZAYQAjAjAwAAQAxAAAjgjQAigiABgxQgBgwgigjQgjgigxgBQgwABgjAig");
	this.shape_56.setTransform(280.45,15.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ligal, new cjs.Rectangle(1.2,-2.3,292.1,31.8), null);


(lib.gazprom_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhrCcIAAhJIGvAAIAABJgAEVCPIALAAQAJAAADgDQAEgCAAgIIAAgEQAAgIgDgCQgDgDgJAAIgBAAIAAgSIgLAAgAC5BoIAJAAIAAAnIALAAIAAgnIAIAAIAAgJIgcAAgABnBjQgJAAgDACQgEADAAAHIAAAPQAAAMAQAAIAAAFIAKAAIAAgFQAQAAAAgMIAAgPQAAgHgEgDQgDgCgJAAIAAgEIgKAAgAADCPIAaAAIAAgJIgOAAIAAgMIANAAIAAgJIgNAAIAAgJIAOAAIAAgJIgaAAgAhHB6IAAAVIALAAIAAgwIgLAAIAAASIgGAAIAAgSIgLAAIAAAwIALAAIAAgVgAkjB9QggghAAgtQAAgtAggeQAfggAtAAIAABQQgZABgSARQgEAEgDAFQgMASACAWQACAWAPAQQASASAZAAQAaAAARgSIAAAAQAJgJAAgNQAAgNgJgIQgJgKgMABQgNgBgJAKIAAgjIBPAAIAABKQghAjguAAQgtAAgfgfgAEgCGIAAgMIACAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAGQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAgABxCBIAAgWIACAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAQQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAgABlCBQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAgQQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIABAAIAAAWgAEvAvIAAhDIgBAAIgLBDIgQAAIgLhDIgBAAIAABDIgUAAIAAhsIAbAAIANBLIAOhLIAbAAIAABsgADGAvQgQAAAAgTIAAhGQAAgSAQgBIARAAQAPABAAASIAABGQAAATgPAAgADKgrIAABIQAAAEAEABQAGgBgBgEIAAhIQAAgEgFAAQgDAAgBAEgAB6AvIAAhsIAhAAQARABAAASIAAAiQAAASgRAAIgMAAIAAAlgACPgBIAFAAQAEAAAAgGIAAgjQAAgFgEAAIgFAAgABYAvIAAheIgJAAIAABeIgUAAIAAhsIAwAAIAABsgAANAvQgOAAAAgTIAAgTIATAAIAAAUQAAAEAEABQADgBAAgEIAAgZQAAgGgIAAIgJAAIAAgMIAJAAQAEAAACgCQACgBAAgFIAAgVQAAgBAAgBQgBgBAAAAQgBgBAAAAQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAgBABQAAABAAABIAAARIgTAAIAAgPQAAgUAOAAIARAAQAPAAAAAUIAAARQAAAQgOgBIAAABQAOgBAAAPIAAAWQAAATgPAAgAgfAvIgCgdIgJAAIgCAdIgVAAIALhsIAhAAIALBsgAgqAHIAJAAIgEg2IgBAAgAhrAvIAAhsIAnAAIAAAOIgSAAIAABegAjAAKQgJgXgDgWQgEgkAKgjQAHgXAQgaIACACQASAeAGAYQAHAigEAhQgGArgXAeQgKgNgHgSgAi0gYQgEALABAMQAAARAIASQAJgRAAgUQgBgTgIgOQgCADgDAJgAjAhiQgFASgBATQAAAXADATQAAgaAEgRQAGgdAKgQQAFAHAFAOQAFAOACAKQAFAXgCATQADgJABgVQAAgagHgXQgFgVgMgUQgJAQgIAag");
	this.shape.setTransform(32.375,15.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gazprom_logo, new cjs.Rectangle(0,0,64.8,31.2), null);


(lib.bg_pic = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.instance = new lib.Растровоеизображение1();
	this.instance.setTransform(-240,-180,0.7805,0.7805);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg_pic, new cjs.Rectangle(-240,-180,480,359.8), null);


(lib.bg_blue = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0070BA").s().p("EgY/AlgMAAAhK/MAx/AAAMAAABK/g");
	this.shape.setTransform(970.1,194,1,1,0,0,0,810.1,-46);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.bg_blue, new cjs.Rectangle(0,0,320,480), null);


(lib.tx13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Слой_1
	this.s1 = new lib.s1();
	this.s1.name = "s1";
	this.s1.setTransform(71.7,17.7,1,1,0,0,0,71.7,17.7);

	this.s2 = new lib.s3();
	this.s2.name = "s2";
	this.s2.setTransform(119.5,58.55,1,1,0,0,0,119.5,13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.s2},{t:this.s1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx13, new cjs.Rectangle(0,0,239,72.4), null);


(lib.tx1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// tx1_2
	this.tx1_2 = new lib.tx12();
	this.tx1_2.name = "tx1_2";
	this.tx1_2.setTransform(252.6,65.9,1,1,0,0,0,252.6,45.2);

	this.timeline.addTween(cjs.Tween.get(this.tx1_2).wait(1));

	// tx1_3
	this.tx1_3 = new lib.tx13();
	this.tx1_3.name = "tx1_3";
	this.tx1_3.setTransform(385.75,136.6,1,1,0,0,0,119.5,36.1);

	this.timeline.addTween(cjs.Tween.get(this.tx1_3).wait(1));

	// tx1_1
	this.tx1_1 = new lib.tx11();
	this.tx1_1.name = "tx1_1";
	this.tx1_1.setTransform(93.2,14.3,1,1,0,0,0,93.2,14.3);

	this.timeline.addTween(cjs.Tween.get(this.tx1_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tx1, new cjs.Rectangle(0,0,505.3,172.9), null);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gazprom_logo
	this.logo = new lib.gazprom_logo();
	this.logo.name = "logo";
	this.logo.setTransform(-0.2,-3.9,1.1734,1.173,0,0,0,32.2,15.5);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// gazprom_logo_bg
	this.bg_blue = new lib.bg_blue();
	this.bg_blue.name = "bg_blue";
	this.bg_blue.setTransform(56.2,21.2,0.35,0.125,0,0,0,320.6,409.6);

	this.timeline.addTween(cjs.Tween.get(this.bg_blue).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-56,-30,112,60), null);


// stage content:
(lib.terra_480x320 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		var root = this;
		
		var tl = gsap.timeline({repeat:-1});
		
		tl
			.to(root.bg_pic, 18, {scaleX:"1.3", scaleY:"1.3", ease:"none"}, "0")
			.to(root.bg_blue1, 0.3, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.tx2, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.shad2, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0.1")
			.from(root.logo, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.ligal, 0.1, {alpha:0.0, ease:"Power1.easeOut"}, "0")
			.from(root.tx1, 1.5, {x:"+=770", ease:"Power3.easeOut"}, "0.3")
			.from(root.tx1.tx1_1, 1.0, {y:"+=20", alpha:0.0, ease:"Power1.easeOut"}, "2.5")
			.from(root.shad1, 1.7, {alpha:0.0, ease:"Power1.easeOut"}, "0.3")
			.from(root.tx1.tx1_3.s2, 1.0, {y:"-=20", alpha:0.0, ease:"Power1.easeOut"}, "1.5")
			.from(root.tx1.tx1_3.s1, 1.0, {y:"-=20", alpha:0.0, ease:"Power1.easeOut"}, "1.7")
		
		
			
			.to(root.logo.bg_blue, 1.2, {scaleX:"2", scaleY:"1", ease:"Power3.easeOut"}, "12")
			.to(root.logo.logo, 1.2, {scaleX:"2.2", scaleY:"2.2", x: "-=196", y: "-=135", ease:"Power3.easeOut"}, "12")
			.from(root.bg_blue2, 0.3, {alpha:0.0, ease:"Power1.easeOut"}, "17.7")
		
		
		;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// bord
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#041418").ss(2,2,0,1).p("EglfgY/MBK/AAAMAAAAx/MhK/AAAg");
	this.shape.setTransform(240,160);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// bg_blue1___копия
	this.bg_blue2 = new lib.bg_blue();
	this.bg_blue2.name = "bg_blue2";
	this.bg_blue2.setTransform(0,0,1.2,0.6666);

	this.timeline.addTween(cjs.Tween.get(this.bg_blue2).wait(1));

	// bg_blue1
	this.bg_blue1 = new lib.bg_blue();
	this.bg_blue1.name = "bg_blue1";
	this.bg_blue1.setTransform(0,0,1.5,0.6667);

	this.timeline.addTween(cjs.Tween.get(this.bg_blue1).wait(1));

	// logo
	this.logo = new lib.logo();
	this.logo.name = "logo";
	this.logo.setTransform(426.3,279.95,0.95,0.9497,0,0,0,0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// tx2
	this.tx2 = new lib.tx2();
	this.tx2.name = "tx2";
	this.tx2.setTransform(61.85,37.1,0.7,0.6998,0,0,0,53,21.4);

	this.timeline.addTween(cjs.Tween.get(this.tx2).wait(1));

	// shad1
	this.shad2 = new lib.shad1();
	this.shad2.name = "shad2";
	this.shad2.setTransform(238.7,64.25,0.5593,0.2918,0,0,0,314.2,106.8);
	this.shad2.alpha = 0.7891;

	this.timeline.addTween(cjs.Tween.get(this.shad2).wait(1));

	// ligal
	this.ligal = new lib.ligal();
	this.ligal.name = "ligal";
	this.ligal.setTransform(191.55,294.05,0.8,0.7978,0,0,0,222.4,8.4);
	this.ligal.alpha = 0.7891;

	this.timeline.addTween(cjs.Tween.get(this.ligal).wait(1));

	// Слой_9 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A9IQUIAA0kMA/RAAAIAAUkg");
	mask.setTransform(218.5316,104.45);

	// tx1
	this.tx1 = new lib.tx1();
	this.tx1.name = "tx1";
	this.tx1.setTransform(240,150.05,0.65,0.6494,0,0,0,252.6,86.5);

	var maskedShapeInstanceList = [this.tx1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.tx1).wait(1));

	// shad1
	this.shad1 = new lib.shad1();
	this.shad1.name = "shad1";
	this.shad1.setTransform(207.75,140.7,1.0355,0.2919,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.shad1).wait(1));

	// terra_bg_970_jpg
	this.bg_pic = new lib.bg_pic();
	this.bg_pic.name = "bg_pic";
	this.bg_pic.setTransform(240.1,170.2,0.9999,0.9998,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.bg_pic).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(199.5,139.1,281.5,210.79999999999998);
// library properties:
lib.properties = {
	id: 'AC5308E581C9DC4DB5D44204AB0025B1',
	width: 480,
	height: 320,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"index_atlas_1.jpg", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['AC5308E581C9DC4DB5D44204AB0025B1'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;